from web3 import Web3

# Connect to the public Base network RPC
base_rpc_url = "https://mainnet.base.org"
w3 = Web3(Web3.HTTPProvider(base_rpc_url))

# The address generated by your Thetanuts CLI
wallet_address = "0x0a750b2F6D1Adfc95264A8bE8fe18784dFCe6B26"

# Verify connection and fetch balance
if w3.is_connected():
    balance_wei = w3.eth.get_balance(wallet_address)
    balance_eth = w3.from_wei(balance_wei, 'ether')
    print(f"Successfully connected to Base.")
    print(f"Balance for {wallet_address}: {balance_eth} ETH")
else:
    print("Failed to connect to the Base network RPC.")